version: '3.8'
services: 
  stockflow-api:
    image: joaovsj/stockflow-api:1.0
    ports: 
      - "8000:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: warehouse
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: