version: '3.8'
services: 
  stockflow-api:
    build: .
    container_name: stockflow-api
    ports: 
      - "8000:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql_stock
    restart: always
    environment:
      MYSQL_DATABASE: warehouse
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: